### ISSUE TITLE
Component naming convention

### ISSUE THREAD

**Issue by hiendv** [hamzoni/Web-Front-End-Assignment#1]
Can you reference the current component naming convention? Why do they start with an `I`?

**Comment by taquy** [comment]
I put letter i before those component name to differ them with html tags

**Comment by hiendv** [comment]
They are HTML tags.

**Comment by hiendv** [comment]
Incorrect: https://github.com/hamzoni/Web-Front-End-Assignment/blob/7121a3c6831f93d40ab6052cc506182948ed3e4a/src/App.vue#L3-L5

**Comment by hiendv** [comment]
OK
