### ISSUE TITLE
Don't reset arrays before replacing

### ISSUE THREAD

**Issue by hiendv** [hamzoni/Web-Front-End-Assignment#10]
Avoid resetting arrays like this: https://github.com/hamzoni/Web-Front-End-Assignment/blob/master/src/components/pages/Albumn.vue#L58-L72
Why? https://vuejs.org/v2/guide/list.html#Replacing-an-Array

**Comment by taquy** [comment]
Thanks for advice.

Updated:
from: 
this.photos = []
to
this.photos.splice(0, this.photos.length);

**Comment by hiendv** [comment]
https://github.com/hamzoni/Web-Front-End-Assignment/blob/44db35ad9e3817844da1b49b0d2096a4e95f10a4/src/components/pages/Album.vue#L64
Should not be defined here. Move it to the next block.

**Comment by hiendv** [comment]
OK
