### ISSUE TITLE
Need better data chunking mechanism

### ISSUE THREAD

**Issue by hiendv** [hamzoni/Web-Front-End-Assignment#12]
https://github.com/hamzoni/Web-Front-End-Assignment/blob/master/src/components/pages/Albumn.vue#L65-L72
What if we decide that there should be `n` photos in a line instead of 4? Replacing 3 times?

**Comment by taquy** [comment]
variables added for better data chunking machanism

numberOfRows: 3,
imagesPerRow: 4

**Comment by hiendv** [comment]
How about this: https://lodash.com/docs/4.17.4#chunk

**Comment by taquy** [comment]
lodash used in last commit.

**Comment by hiendv** [comment]
We don't actually need `lodash/array`. Try this:
https://www.npmjs.com/package/lodash.chunk

**Comment by taquy** [comment]
updated package.json: removed lodash dependency

**Comment by hiendv** [comment]
OK
