### ISSUE TITLE
Inappropriate default values

### ISSUE THREAD

**Issue by hiendv** [hamzoni/Web-Front-End-Assignment#13]
https://github.com/hamzoni/Web-Front-End-Assignment/blob/master/src/components/pages/Profile.vue#L61-L71
Default values or prop definitions should indicate types and respectively zero-values.

**Comment by taquy** [comment]
Thanks for suggestion.
New updated is:
```
followers: 0,
following: 0,
downloads: 0,
```

**Comment by hiendv** [comment]
How about these:
https://github.com/hamzoni/Web-Front-End-Assignment/blob/510f01a07ead84e69efb6f2b0949b0930656473c/src/components/partials/Pagination.vue#L62-L67

**Comment by taquy** [comment]
These I made on purpose. 
For example: v-if="localPag.last" or :disabled="!localPag.next"

**Comment by hiendv** [comment]
No need to be undefined.
