### ISSUE TITLE
HTML Markup Errors

### ISSUE THREAD

**Issue by hiendv** [hamzoni/Web-Front-End-Assignment#14]
Potential duplicated IDs: https://github.com/hamzoni/Web-Front-End-Assignment/blob/master/src/components/partials/ImageBox.vue#L2

Misused anchors: https://github.com/hamzoni/Web-Front-End-Assignment/blob/master/src/components/partials/ImageBox.vue#L13-L17

**Comment by taquy** [comment]
In fact the class name and ID name are distinct.
anchors is used for styling I suppose, as Bulma.io defined a default style for the tag.

**Comment by hiendv** [comment]
OK
