### ISSUE TITLE
Pagination improvements

### ISSUE THREAD

**Issue by hiendv** [hamzoni/Web-Front-End-Assignment#17]
- Computed property instead of a watch: https://github.com/hamzoni/Web-Front-End-Assignment/blob/master/src/components/partials/Pagination.vue#L72

**Comment by haicon232** [comment]
Return giá trị zero value phù hợp:
https://github.com/hamzoni/Web-Front-End-Assignment/blob/5d6fa85914ea34070746bec490fbda225c5b6752/src/components/partials/Pagination.vue#L78

**Comment by hiendv** [comment]
- ECMAScript consistency: https://github.com/hamzoni/Web-Front-End-Assignment/blob/5d6fa85914ea34070746bec490fbda225c5b6752/src/components/partials/Pagination.vue#L65
- Fail fast / Return early: https://github.com/hamzoni/Web-Front-End-Assignment/blob/5d6fa85914ea34070746bec490fbda225c5b6752/src/components/partials/Pagination.vue#L66-L83
- Map is not quite suitable. Try forEach: https://github.com/hamzoni/Web-Front-End-Assignment/blob/5d6fa85914ea34070746bec490fbda225c5b6752/src/components/partials/Pagination.vue#L69

**Comment by taquy** [comment]
Another attempt for Fail fast / Return early issue in last commit.

**Comment by taquy** [comment]
Again

**Comment by hiendv** [comment]
Looks good to me.
