### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by haicon232** [hamzoni/Web-Front-End-Assignment#18]
Viết CSS dài quá. Em có thể viết gọn lại được không?
https://github.com/hamzoni/Web-Front-End-Assignment/blob/master/src/components/partials/Loader.vue

Có thể sử dụng SASS function được không?
http://thesassway.com/advanced/pure-sass-functions

**Comment by hiendv** [comment]
More correct reference:
https://github.com/hamzoni/Web-Front-End-Assignment/blob/44e2a55a6a4ac69b3e52b61bdb82808ae10a548a/src/components/partials/Loader.vue

**Comment by taquy** [comment]
Code CSS này của 1 party khác, có nhất thiết phải tối ưu ko ạ?

**Comment by hiendv** [comment]
Sẽ là technical debt trong tương lai. Cần được tối ưu nhưng priority thấp. Tạm thời close - non-accepted.
