### ISSUE TITLE
Validate data

### ISSUE THREAD

**Issue by haicon232** [hamzoni/Web-Front-End-Assignment#19]
https://github.com/hamzoni/Web-Front-End-Assignment/blob/master/src/components/partials/ImageBox.vue

Nhớ validate data trước khi sử dụng.
VD: https://github.com/hamzoni/Web-Front-End-Assignment/blob/master/src/components/partials/ImageBox.vue#L44

Nếu 

this.info undefined thì sao?
this.info.user undefined thì sao?
this.info.user.first_name undefined thì sao?

**Comment by hiendv** [comment]
It's called defensive programming.

**Comment by hiendv** [comment]
https://github.com/hamzoni/Web-Front-End-Assignment/blob/e6b397f212f49c1aaa6db16823178d2f97066c6c/src/components/partials/ImageBox.vue#L34-L93
- ECMAScript Standard Consistency
- Fail fast / Return early

**Comment by taquy** [comment]
Another Attempt for Fail fast / Return early in last commit

**Comment by taquy** [comment]
Again

**Comment by hiendv** [comment]
https://github.com/hamzoni/Web-Front-End-Assignment/blob/e85a7241f6c530f13ee5326d93f9e5f209a30d7a/src/components/ImageBox.vue#L46
Definitely error

**Comment by taquy** [comment]
Yes, I've fixed it.
