### ISSUE TITLE
Replace moment.js by date-fns

### ISSUE THREAD

**Issue by hiendv** [hamzoni/Web-Front-End-Assignment#2]
Reasons:
- Immutability
- Tree-shaking / Bundle size
- Clean API

Related:
- https://github.com/chartjs/Chart.js/issues/4303
- https://github.com/date-fns/date-fns/issues/275

**Comment by taquy** [comment]
Old code: 
created: new Moment(new Date(this.info.created_at).valueOf()).format("LTS ll"),
updated: new Moment(new Date(this.info.updated_at).valueOf()).format("LTS ll")

Updated code:
created: DateFNS.format(DateFNS.parse(this.info.created_at), "hh:mm:ss A MMM Do YYYY"),
updated: DateFNS.format(DateFNS.parse(this.info.updated_at), "hh:mm:ss A MMM Do YYYY")

**Comment by hiendv** [comment]
- Moment still exists: https://github.com/hamzoni/Web-Front-End-Assignment/blob/master/package.json#L13
- Incorrect expected imports for sub modules: https://github.com/hamzoni/Web-Front-End-Assignment/blob/master/src/components/partials/ImageBox.vue#L28
See: https://github.com/date-fns/date-fns/blob/master/docs/gettingStarted.md#submodules
- Do not export unused variables: https://github.com/hamzoni/Web-Front-End-Assignment/blob/master/src/components/partials/ImageBox.vue#L30

**Comment by hiendv** [comment]
OK
