### ISSUE TITLE
Chia thư mục chưa hợp lý

### ISSUE THREAD

**Issue by haicon232** [hamzoni/Web-Front-End-Assignment#20]
Sao Pages lại ở trong Components vậy?
Components chỉ chứa các Components thôi nhé.
Pages sử dụng Components cơ mà?

**Comment by hiendv** [comment]
```
/src
    /components
    /pages
    ...
````

**Comment by taquy** [comment]
theo tutorial thì mọi cái file có đuôi .vue đều cho hết vào components anh ạ 
còn về ý nghĩa của nó thì em nghĩ .. các anh biết đấy, pages với partials đã nói khá rõ rồi

**Comment by hiendv** [comment]
Chỗ này cần thảo luận nhiều hơn. Theo anh và structute hiện tại của các project trong CyRadar, `pages` nên chứa các trang trong khi `components` chứa các shared components, dùng >= 1 lần. Việc mặc định đuôi phải vào components anh nghĩa là hơi cứng nhắc. Viết như này e sẽ giảm bớt được một level của path, đồng thời bỏ qua đc thư mục như partials (được inspired từ Laravel nếu anh nhớ không nhầm).

**Comment by taquy** [comment]
ok anh , nhất trí quan điểm

**Comment by hiendv** [comment]
OK
