### ISSUE TITLE
Consistency when defining dependencies and devDependencies

### ISSUE THREAD

**Issue by hiendv** [hamzoni/Web-Front-End-Assignment#4]
- What's the difference between dependencies and devDependencies?
- What's the difference between application & library dependencies?
- How does the build system affect the process of defining dependencies?

**Comment by taquy** [comment]
Answer #1:
- devDependencies:
command: npm install `package-name` --dev
Def:
has the same properties as dependencies but with several distinct features
distinction:  
+ to develop, e.g.: unit tests, Coffeescript to Javascript transpilation, minification, ...
+ to exclude external test or documentation framework of the module
thus, without defining devDependencies, these dependencies are installed for end-user (?)
- dependencies:
command: npm install `package-name`
Def: 
Dependencies are Libraries and Tools (other Programs) of a program that relies on to work.
Dependencies are specified with a simple hash of package name to version range.

Answer #2:
Application dependencies: is a list of other applications that are required for this application to properly work. In this program, the one of the dependency of this program is Node JS engine.
Library dependencies: similar to Application dependencies, these are dependencies that are required for the library properly working. For example: the bootstrap css framework is only properly works if it has Jquery library available (to unlock such feature like Modal)

Answer #3:
I could not find a proper answer for this question.


 build systems are a functional based languages mapping a set of source resources (in most cases, files) to a target (executable).

**Comment by hiendv** [comment]
- Moment.js still exists: https://github.com/hamzoni/Web-Front-End-Assignment/blob/master/package.json#L13
- Do not export if it's not needed: https://github.com/hamzoni/Web-Front-End-Assignment/blob/4e80dd7a7b95b2e7669fb923294ca3cbd707cdbd/src/components/partials/ImageBox.vue#L30
- Incorrect expected import with submodules: https://github.com/hamzoni/Web-Front-End-Assignment/blob/4e80dd7a7b95b2e7669fb923294ca3cbd707cdbd/src/components/partials/ImageBox.vue#L28
Try this https://github.com/date-fns/date-fns/blob/master/docs/gettingStarted.md#submodules

**Comment by hiendv** [comment]
1. In nodejs world, `dependencies` are mandatory to **run** the application, `devDependencies` are only needed for development only. For example, with a script.js
```js
const something = require('a-package')
console.log(something)
```
```bash
node script.js # will return error if the a-package is not installed
```

But instead of running the script, we build the script with a bundler for example, then run like this
```bash
node bundle.js # will not return the error since the a-package is concatenated into the bundle.js when developing
```
