### ISSUE TITLE
Consistency when naming component

### ISSUE THREAD

**Issue by hiendv** [hamzoni/Web-Front-End-Assignment#7]
You may want to use either dash-separated or PascalCase, not both.

**Comment by taquy** [comment]
Depends on the case I think, these are my preferences (but ofc I will take your advice as consistency naming): 

camelCase is chosen for declaring variable and function name.
underscore_separted for sql fields name or api data
dash-separated for template (html) tag or class name.
PascalCase for components name. (as Class name is often chose this form as practice of writing)

**Comment by hiendv** [comment]
- Menubar is not a word: https://github.com/hamzoni/Web-Front-End-Assignment/blob/master/src/components/IHeader.vue#L15
- Attribute is not written in dash-separated format: https://github.com/hamzoni/Web-Front-End-Assignment/blob/master/src/components/partials/AlbumFrame.vue#L2
- Component name is not written in camelCase: https://github.com/hamzoni/Web-Front-End-Assignment/blob/master/src/components/pages/Album.vue#L34
---
These are some noticeable mistakes, there are more, find and fix them.

**Comment by hiendv** [comment]
Correct the second reference: https://github.com/hamzoni/Web-Front-End-Assignment/blob/2ead08afc4352684579ec0707d246411aff69fac/src/components/partials/AlbumFrame.vue#L2
As I already said, there are more.

**Comment by hiendv** [comment]
Some I can find:
- https://github.com/hamzoni/Web-Front-End-Assignment/blob/0bae3d2321aef485e4ad262f74ec72e175beeb72/src/components/pages/Profile.vue#L2
- https://github.com/hamzoni/Web-Front-End-Assignment/blob/90c1e624e6086765ab663684382d05d4e90cc648/src/components/partials/Navigator.vue#L23
There may be more.
